### ISSUE TITLE
CRUD Users

### ISSUE THREAD

**Issue by guigrubba** [S204-Inatel-2024-1/SemPressaApp#8]
COlunas:

- nome
- email
- senha
- curso: não obrigatório
- matricula ( index )
- id
- role: padrão aluno
- foto: não obrigatório ( futuro )

**Comment by guigrubba** [comment]
fiz um crud de usuario, por enquanto a rota do crud é /user. Pode ser que mude de acordo com a necessidade

**Comment by Edukarp** [comment]
Testes de Create, Update, Read e Delete Funcionando
Falta adicionar o tipo de email valido
